version: '2'
services:
  wenshu:
    image: weihanli/puppeteer:node12-slim-stable
    container_name: TProjectName
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_HEADLESS=true
    ports:
      - 10240:3000
    volumes:
      - .:/app
