trigger:
  branches:
    include:
    - '*' # must quote since "*" is a YAML reserved character; we want a string
  paths:
    exclude:
    - '*.md'
    - /docs/

pool:
  vmImage: 'windows-2019'

steps:
- script: dotnet --info
  displayName: 'dotnet info'

- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    Nuget__ApiKey: $(nugetApiKey)
    Nuget__SourceUrl: $(nugetSourceUrl)
